PPcore/src/PPcore/Models/project.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PPcore.Models
{
    public partial class project
    {
        [Display(Name = "รหัสโครงการ")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        public string project_code { get; set; }
        [Display(Name = "ชื่อโครงการ")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        public string project_desc { get; set; }
        [Display(Name = "วันที่จัดตั้งโครงการ")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime? project_date { get; set; }
        [Display(Name = "วันที่อนุมัติโครงการ")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime? project_approve_date { get; set; }
        [Display(Name = "เอกสารอ้างอิง")]
        public string ref_doc { get; set; }
        [Display(Name = "งบประมาณ")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        //[DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal? budget { get; set; }
        [Display(Name = "ผู้รับผิดชอบโครงการ")]
        public string project_manager { get; set; }
        [Display(Name = "จำนวนเป้าหมายผู้เข้าร่วมโครงการ")]
        public int? target_member_join { get; set; }
        [Display(Name = "จำนวนผู้ลงทะเบียนเข้าร่วมโครงการ")]
        public int? active_member_join { get; set; }
        [Display(Name = "จำนวนผู้ที่สอบผ่าน")]
        public int? passed_member { get; set; }
        [Display(Name = "สถานะ")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        public string x_status { get; set; }
        public string x_note { get; set; }
        public string x_log { get; set; }
        [HiddenInput]
        public Guid id { get; set; }
    }
}

PPcore/src/PPcore/ViewModels/project/project_supporterViewModel.cs
using System.ComponentModel.DataAnnotations;


namespace PPcore.ViewModels.project
{
    public class project_supporterViewModel
    {
        public Models.project project { get; set; }

        [Display(Name = "งบประมาณ")]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        //[DisplayFormat(DataFormatString = "{0:N0}")]
        public decimal? support_budget { get; set; }
    }
}

PPcore/src/PPcore/Controllers/projectsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPcore.Models;

namespace PPcore.Controllers
{
    public class projectsController : Controller
    {
        private readonly PalangPanyaDBContext _context;

        public projectsController(PalangPanyaDBContext context)
        {
            _context = context;    
        }

        public IActionResult Index()
        {
            ViewBag.countRecords = _context.project.Count();
            return View();
        }

        [HttpGet]
        public IActionResult DetailsAsTable()
        {
            var ps = _context.project.OrderBy(m => m.project_code).ToList();
            foreach (project p in ps)
            {
                int countJoin = 0; int countPassed = 0;
                var pcs = _context.project_course.Where(pss => pss.project_code == p.project_code).ToList();
                foreach (project_course pc in pcs)
                {
                    countJoin += _context.project_course_register.Where(pcr => pcr.course_code == pc.course_code).Count();
                    countPassed += _context.project_course_register.Where(pcrr => (pcrr.course_code == pc.course_code) && (pcrr.course_grade >= pc.passed_score)).Count();
                }
                p.active_member_join = countJoin;
                p.passed_member = countPassed;
            }
            return View(ps);
        }

        [HttpGet]
        public IActionResult DetailsAsTableBySponsor(string spon_code)
        {
            var pss = _context.project_supporter.Where(mps => mps.spon_code == spon_code).ToList();
            List<ViewModels.project.project_supporterViewModel> pjs = new List<ViewModels.project.project_supporterViewModel>();
            foreach (project_supporter ps in pss)
            {
                var p = _context.project.SingleOrDefault(m => m.project_code == ps.project_code);
                ViewModels.project.project_supporterViewModel v = new ViewModels.project.project_supporterViewModel();
                v.project = p;
                v.support_budget = ps.support_budget;
                pjs.Add(v);
            }
            return View("DetailsAsTableBySponsor", pjs.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("project_code,active_member_join,budget,id,passed_member,project_approve_date,project_date,project_desc,project_manager,ref_doc,target_member_join,x_log,x_note,x_status")] project project)
        {
            if (ModelState.IsValid)
            {
                _context.Add(project);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(project);
        }

        public async Task<IActionResult> Edit(string id, string v)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.project.SingleOrDefaultAsync(m => m.id == new Guid(id));
            if (project == null)
            {
                return NotFound();
            }
            int countJoin = 0; int countPassed = 0;
            var ps = _context.project_course.Where(pss => pss.project_code == project.project_code).ToList();
            foreach (project_course p in ps)
            {
                countJoin += _context.project_course_register.Where(pcr => pcr.course_code == p.course_code).Count();
                countPassed += _context.project_course_register.Where(pcrr => (pcrr.course_code == p.course_code) && (pcrr.course_grade >= p.passed_score)).Count();
            }
            ViewBag.active_member_join = countJoin;
            ViewBag.passed_member = countPassed;
            if (!String.IsNullOrEmpty(v)) { ViewBag.IsDetails = true;  } else { ViewBag.IsDetails = false; }
            return View(project);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id, [Bind("project_code,active_member_join,budget,id,passed_member,project_approve_date,project_date,project_desc,project_manager,ref_doc,target_member_join,x_log,x_note,x_status")] project project)
        {
            if (new Guid(id) != project.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(project);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!projectExists(project.project_code))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(project);
        }

        // GET: projects/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project = await _context.project.SingleOrDefaultAsync(m => m.project_code == id);
            if (project == null)
            {
                return NotFound();
            }

            return View(project);
        }

        // POST: projects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var project = await _context.project.SingleOrDefaultAsync(m => m.project_code == id);
            _context.project.Remove(project);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool projectExists(string id)
        {
            return _context.project.Any(e => e.project_code == id);
        }
    }
}

PPcore/src/PPcore/Views/projects/Create.cshtml
@model PPcore.Models.project

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12" style="padding-top:15px;">
            <table><tr><td><h4 class="txt-color-blue">ข้อมูลโครงการและผู้สนับสนุน</h4></td><td class="txt-color-blue" style="padding-top:2px">&nbsp;&nbsp;&nbsp;&nbsp;เพิ่มข้อมูลโครงการและผู้สนับสนุน</td></tr></table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-body">
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a data-toggle="tab">โครงการ</a>
                            </li>
                        </ul>
                    <div style="background-color:#093D6A;height:8px;"></div>
                    <br />
                    <div id="renderBody">

                        <form asp-action="Create">
                            <div class="pull-right" style="margin-top:-72px;">
                                <button id="btnSave" type="submit" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-floppy-o" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;จัดเก็บ&nbsp;&nbsp;</button>
                                <div id="btnDetails" class="btn btn-default btn-panel-yellow" onclick="location.href='@Url.Action("Index", "projects")'">&nbsp;<i class="fa fa-file-text" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;ดูข้อมูลทั้งหมด</div>
                            </div>
                            <div class="form-horizontal">
                                <br />
                                <div class="row">
                                    <div class="col-md-offset-1 col-md-8">
                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-2 text-right"><label asp-for="project_code" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="project_code" class="form-control" />
                                                    <span asp-validation-for="project_code" class="text-danger" />
                                                </div>
                                                <div class="col-md-2 text-right"><label asp-for="project_date" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <div class="input-group">
                                                        <input asp-for="project_date" class="form-control" readonly style="background-color:white">
                                                        <span class="input-group-btn">
                                                            <button id="project_date_button" class="btn btn-default" type="button">
                                                                <i class="fa fa-calendar"></i>
                                                            </button>
                                                        </span>
                                                    </div>
                                                    <span asp-validation-for="project_date" class="text-danger" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-2 text-right"><label asp-for="project_desc" class="control-label"></label></div>
                                                <div class="col-md-10">
                                                    <input asp-for="project_desc" class="form-control" />
                                                    <span asp-validation-for="project_desc" class="text-danger" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-2 text-right"><label asp-for="project_approve_date" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <div class="input-group">
                                                        <input asp-for="project_approve_date" class="form-control" readonly style="background-color:white">
                                                        <span class="input-group-btn">
                                                            <button id="project_approve_date_button" class="btn btn-default" type="button">
                                                                <i class="fa fa-calendar"></i>
                                                            </button>
                                                        </span>
                                                    </div>
                                                    <span asp-validation-for="project_approve_date" class="text-danger" />
                                                </div>
                                                <div class="col-md-2 text-right"><label asp-for="ref_doc" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="ref_doc" class="form-control" />
                                                    <span asp-validation-for="ref_doc" class="text-danger" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-2 text-right"><label asp-for="budget" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="budget" class="form-control" />
                                                    <span asp-validation-for="budget" class="text-danger" />
                                                </div>
                                                <div class="col-md-2 text-right"><label asp-for="project_manager" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="project_manager" class="form-control" />
                                                    <span asp-validation-for="project_manager" class="text-danger" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-2 text-right"><label asp-for="target_member_join" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="target_member_join" class="form-control" />
                                                    <span asp-validation-for="target_member_join" class="text-danger" />
                                                </div>
                                                <div class="col-md-2 text-right"><label asp-for="active_member_join" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="active_member_join" class="form-control" disabled="disabled" />
                                                    <span asp-validation-for="active_member_join" class="text-danger" />
                                                </div>
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <div class="row">
                                                <div class="col-md-2 text-right"><label asp-for="passed_member" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <input asp-for="passed_member" class="form-control" disabled="disabled"/>
                                                    <span asp-validation-for="passed_member" class="text-danger" />
                                                </div>
                                                <div class="col-md-2 text-right"><label asp-for="x_status" class="control-label"></label></div>
                                                <div class="col-md-4">
                                                    <select asp-for="x_status" class="form-control" asp-items="@Html.x_status_SelectList()"></select>
                                                </div>
                                            </div>
                                        </div>

                                    </div>
                                </div>



                            </div>


                        </form>



                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


@section scripts {
    <script src="~/lib/bootstrap/js/modal.js"></script>
    <script>
        $(document).ready(function () {
            $.datepicker.regional['th'] = {
                dateFormat: 'dd-mm-yy', changeMonth: true, changeYear: true, constrainInput: true,
                yearRange: "-100:+1", yearOffSet: 543, beforeShow: dateDefault
            };
            $.datepicker.setDefaults($.datepicker.regional['th']);
            $("#project_date").datepicker($.datepicker.regional["th"]);
            $('#project_date_button').off('click').on('click', function () {
                $('#project_date').datepicker("show");
            });

            $("#project_approve_date").datepicker($.datepicker.regional["th"]);
            $('#project_approve_date_button').off('click').on('click', function () {
                $('#project_approve_date').datepicker("show");
            });
        });
        function dateDefault() {
            if ($("#project_date").val() == "" && ($("#project_date").is(":focus") || $("#project_date_button").is(":focus"))) { $("#project_date").datepicker("setDate", new Date()); }
            if ($("#project_approve_date").val() == "" && ($("#project_approve_date").is(":focus") || $("#project_approve_date_button").is(":focus"))) { $("#project_approve_date").datepicker("setDate", new Date()); }
        }
    </script>
}

PPcore/src/PPcore/Views/projects/DetailsAsTable.cshtml
@model IEnumerable<PPcore.Models.project>
@{
    Layout = null;
}

<table class="table table-striped table-bordered table-hover" id="a_table">
    <thead>
        <tr>
            <th style="width:15px;">ลำดับ</th>
            <th style="display:none">@Html.DisplayNameFor(model => model.id)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.project_code)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.project_desc)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.project_date)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.project_approve_date)</th>
            <th>@Html.DisplayNameFor(model => model.budget)</th>
            <th>@Html.DisplayNameFor(model => model.project_manager)</th>
            <th>@Html.DisplayNameFor(model => model.target_member_join)</th>
            <th>@Html.DisplayNameFor(model => model.active_member_join)</th>
            <th>@Html.DisplayNameFor(model => model.passed_member)</th>
            <th style="width:50px;">@Html.DisplayNameFor(model => model.x_status)</th>
        </tr>
    </thead>
    <tbody>
        @{ var countOrder = 0;}
        @foreach (var item in Model)
        {
            countOrder++;
            <tr>
                <td style="width:15px;">
                    @countOrder
                </td>
                <td style="display:none">@Html.DisplayFor(modelItem => item.id)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_desc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_approve_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.budget)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project_manager)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.target_member_join)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.active_member_join)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.passed_member)
                </td>
                <td>@Html.x_status_text(item.x_status)</td>
            </tr>
        }
    </tbody>
</table>

PPcore/src/PPcore/Views/projects/DetailsAsTableBySponsor.cshtml
@model IEnumerable<PPcore.ViewModels.project.project_supporterViewModel>
@{
    Layout = null;
}

<table class="table table-striped table-bordered table-hover" id="a_table">
    <thead>
        <tr>
            <th style="width:15px;">ลำดับ</th>
            <th style="display:none">@Html.DisplayNameFor(model => model.project.id)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.project.project_code)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.project.project_desc)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.project.project_date)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.project.project_approve_date)</th>
            <th>@Html.DisplayNameFor(model => model.support_budget)</th>
            <th>@Html.DisplayNameFor(model => model.project.project_manager)</th>
            <th>@Html.DisplayNameFor(model => model.project.target_member_join)</th>
            <th>@Html.DisplayNameFor(model => model.project.active_member_join)</th>
            <th>@Html.DisplayNameFor(model => model.project.passed_member)</th>
            <th style="width:50px;">@Html.DisplayNameFor(model => model.project.x_status)</th>
        </tr>
    </thead>
    <tbody>
        @{ var countOrder = 0;}
        @foreach (var item in Model)
        {
            countOrder++;
            <tr>
                <td style="width:15px;">
                    @countOrder
                </td>
                <td style="display:none">@Html.DisplayFor(modelItem => item.project.id)</td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.project_code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.project_desc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.project_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.project_approve_date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.support_budget)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.project_manager)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.target_member_join)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.active_member_join)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.project.passed_member)
                </td>
                <td>@Html.x_status_text(item.project.x_status)</td>
            </tr>
        }
    </tbody>
</table>

PPcore/src/PPcore/Views/projects/Index.cshtml
@model PPcore.Models.project

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12" style="padding-top:15px;">
            <table><tr><td><h4 class="txt-color-blue">ข้อมูลโครงการ</h4></td></tr></table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading">
                    <div class="pull-left" style="padding-top:5px;">แสดงข้อมูลทั้งหมด</div>
                    <div class="pull-right" style="margin-top:-2px;">
                        กดปุ่มเพิ่ม ถ้าต้องการใส่มากกว่า 1 รายการ&nbsp;&nbsp;&nbsp;
                        <button id="btnCreate" class="btn btn-default btn-panel-yellow" onclick="location.href='@Url.Action("Create", "projects")'">&nbsp;<i class="fa fa-file" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;&nbsp;เพิ่ม&nbsp;&nbsp;&nbsp;&nbsp;</button>
                        <button id="btnEdit" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-pencil-square-o" aria-hidden="true" style="color:white;"></i>&nbsp;แก้ไข&nbsp;&nbsp;</button>
                        <button id="btnDetails" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-file-text" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;ดูข้อมูล</button>
                    </div>
                </div>

                <!-- /.panel-heading -->
                <div style="position:absolute;left:250px;top:70px;"><span class="badge">จำนวนรายการทั้งหมด @ViewBag.countRecords รายการ</span></div>
                <div class="panel-body">
                    <div class="dataTable_wrapper" style="padding-right:10px;" id="a_details_as_table">



                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
    </div>

</div>

@section scripts {
    <script src="~/lib/bootstrap/js/modal.js"></script>
    <script>
        $(document).ready(function () {
            a_details_as_table();
        });
        function a_details_as_table() {
            $.ajax({
                type: 'get', url: '@Url.Action("DetailsAsTable", "projects")',
            }).done(function (resp) {
                $('#a_details_as_table').html(resp);
                var w = [
                    { "targets": [0], "width": "15", "className": "dt-center" },
                    { "targets": [1], "visible": false, "searchable": false },
                    { "targets": [2], "width": "70", "className": "dt-center" },
                    { "targets": [3], "width": "150" },
                    { "targets": [4], "width": "70", "className": "dt-center" },
                    { "targets": [5], "width": "70", "className": "dt-center" },
                    { "targets": [6], "className": "dt-center" },
                    { "targets": [8], "className": "dt-center" },
                    { "targets": [9], "className": "dt-center" },
                    { "targets": [10], "className": "dt-center" },
                    { "targets": [11], "width": "50", "className": "dt-center" },
                ];
                var table = setTable_default($('#a_table'), w);
                table.$('tr:first').click();
            });
        }
        $('#btnEdit').on('click', function () {
            var table = $('#a_table').DataTable();
            var datarow = table.row('.selected').data();
            window.location.href = "@Url.Action("Edit", "projects")" + "/" + datarow[1];
        });
        $('#btnDetails').on('click', function () {
            var table = $('#a_table').DataTable();
            var datarow = table.row('.selected').data();
            window.location.href = "@Url.Action("Edit", "projects")" + "/" + datarow[1] + "?v=1";
        });
    </script>
}