PPtest/src/PPtest/Controllers/EMailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PPtest.Services;

namespace PPtest.Controllers
{
    public class EMailController : Controller
    {
        private readonly IEmailSender _emailSender;

        public EMailController(IEmailSender emailSender)
        {
            _emailSender = emailSender;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> send()
        {
            await _emailSender.SendEmailAsync("nokflyingtest@gmail.com", "testing", "try to send");
            return View();
        }
    }
}

PPtest/src/PPtest/Controllers/PdfSharpTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MigraDoc;
using MigraDoc.DocumentObjectModel;
using PdfSharp.Pdf;
using MigraDoc.Rendering;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using MigraDoc.DocumentObjectModel.Shapes;
using PdfSharp.Drawing;

namespace PPtest.Controllers
{
    public class PdfSharpTestController : Controller
    {
        private IHostingEnvironment _env;

        public PdfSharpTestController(IHostingEnvironment env)
        {
            _env = env;
        }

        public ActionResult TestMigraDoc1()
        {

            Document document = new Document();

            Style style = document.Styles["Normal"];
            style.Font.Name = "Cordia New";
            style.Font.Size = 16;

            document.Info.Author = "PalangPanya";
            document.Info.Subject = "Member Information";
            document.Info.Keywords = "PalangPanya";

            Section section = document.AddSection();

            Paragraph paragraph = section.AddParagraph();

            paragraph.Format.Font.Color = Color.FromCmyk(100, 30, 20, 50);

            paragraph.AddFormattedText("Hello,ไทย World!", TextFormat.Bold);
            paragraph.AddFormattedText("ทดสอบการใช้ภาษา", TextFormat.Italic);

            var logoPath = Path.Combine(_env.WebRootPath, "images");
            logoPath = Path.Combine(logoPath, "logo_t.png");
            Image imgLogo = section.AddImage(logoPath);
            imgLogo.Height = "2cm";
            imgLogo.LockAspectRatio = true;

            var memberPicPath = Path.Combine(_env.WebRootPath, "images_member");
            memberPicPath = Path.Combine(memberPicPath, "_2_1365148227.jpg");
            //memberPicPath = Path.Combine(memberPicPath, "_677138-topic-ix-1.jpg");
            Image imgMember = section.AddImage(memberPicPath);
            imgMember.Height = "5cm";
            imgMember.LockAspectRatio = true;
            imgMember.RelativeVertical = RelativeVertical.Line;
            imgMember.RelativeHorizontal = RelativeHorizontal.Margin;
            imgMember.Top = ShapePosition.Top;
            imgMember.Left = ShapePosition.Right;
            imgMember.WrapFormat.Style = WrapStyle.Through;


            document.UseCmykColor = true;
            const bool unicode = true;
            const PdfFontEmbedding embedding = PdfFontEmbedding.Always;
            PdfDocumentRenderer pdfRenderer = new PdfDocumentRenderer(unicode, embedding);
            pdfRenderer.Document = document;
            pdfRenderer.RenderDocument();
            //const string filename = "HelloWorld.pdf";
            //pdfRenderer.PdfDocument.Save(filename);
            MemoryStream m = new MemoryStream();
            pdfRenderer.PdfDocument.Save(m,false);
            return new FileStreamResult(m, "application/pdf");
        }

        public ActionResult TestMigraDocMixPdfSharp()
        {
            PdfDocument doc = new PdfDocument();
            doc.Info.Title = "Member information";
            doc.Info.Author = "PalangPanya";
            doc.Info.Subject = "Member information";
            doc.Info.Keywords = "PalangPanya";

            PdfPage page = doc.AddPage();
            XGraphics gfx = XGraphics.FromPdfPage(page);
            gfx.MUH = PdfFontEncoding.Unicode;
            gfx.MFEH = PdfFontEmbedding.Default;
            XFont font = new XFont("Cordia New", 16, XFontStyle.Bold);
            gfx.DrawString("The following paragraph was rendered using ภาษาภ", font, XBrushes.Black,new XRect(100, 100, page.Width - 200, 300), XStringFormats.Center);


            XPen pen = new XPen(XColors.Navy, Math.PI);

    gfx.DrawRectangle(pen, 10, 0, 100, 60);
    gfx.DrawRectangle(XBrushes.DarkOrange, 130, 0, 100, 60);
    gfx.DrawRectangle(pen, XBrushes.DarkOrange, 10, 80, 100, 60);
    gfx.DrawRectangle(pen, XBrushes.DarkOrange, 150, 80, 60, 60);





                Document document = new Document();
                Section sec = document.AddSection();

                //Paragraph para = sec.AddParagraph();
                //para.Format.Alignment = ParagraphAlignment.Justify;
                //para.Format.Font.Name = "Times New Roman";
                //para.Format.Font.Size = 12;
                //para.Format.Font.Color = MigraDoc.DocumentObjectModel.Colors.DarkGray;
                //para.Format.Font.Color = MigraDoc.DocumentObjectModel.Colors.DarkGray;
                //para.AddText("Duisism odigna acipsum delesenisl ");
                //para.AddFormattedText("ullum in velenit", TextFormat.Bold);
                //para.AddText(" ipit iurero dolum zzriliquisis nit wis dolore vel et nonsequipit, velendigna " +
                //  "auguercilit lor se dipisl duismod tatem zzrit at laore magna feummod oloborting ea con vel " +
                //  "essit augiati onsequat luptat nos diatum vel ullum illummy nonsent nit ipis et nonsequis " +
                //  "niation utpat. Odolobor augait et non etueril landre min ut ulla feugiam commodo lortie ex " +
                //  "essent augait el ing eumsan hendre feugait prat augiatem amconul laoreet. ≤≥≈≠");
                //para.Format.Borders.Distance = "5pt";
                //para.Format.Borders.Color = Colors.Gold;





            Paragraph paragraph = sec.AddParagraph();

            paragraph.Format.Font.Color = Color.FromCmyk(100, 30, 20, 50);

            paragraph.AddFormattedText("Hello,ไทย World!", TextFormat.Bold);
            paragraph.AddFormattedText("ทดสอบการใช้ภาษา", TextFormat.Italic);

            var logoPath = Path.Combine(_env.WebRootPath, "images");
            logoPath = Path.Combine(logoPath, "logo_t.png");
            Image imgLogo = sec.AddImage(logoPath);
            imgLogo.Height = "2cm";
            imgLogo.LockAspectRatio = true;

            var memberPicPath = Path.Combine(_env.WebRootPath, "images_member");
            memberPicPath = Path.Combine(memberPicPath, "_2_1365148227.jpg");
            //memberPicPath = Path.Combine(memberPicPath, "_677138-topic-ix-1.jpg");
            Image imgMember = sec.AddImage(memberPicPath);
            imgMember.Height = "5cm";
            imgMember.LockAspectRatio = true;
            imgMember.RelativeVertical = RelativeVertical.Line;
            imgMember.RelativeHorizontal = RelativeHorizontal.Margin;
            imgMember.Top = ShapePosition.Top;
            imgMember.Left = ShapePosition.Right;
            imgMember.WrapFormat.Style = WrapStyle.Through;



            //document.UseCmykColor = true;
            const bool unicode = true;
            const PdfFontEmbedding embedding = PdfFontEmbedding.Always;
            PdfDocumentRenderer pdfRenderer = new PdfDocumentRenderer(unicode, embedding);
            pdfRenderer.Document = document;
            pdfRenderer.RenderDocument();
            

            //MigraDoc.Rendering.DocumentRenderer docRenderer = new DocumentRenderer(document);
            //MigraDoc.Rendering.DocumentRenderer docRenderer = pdfRenderer.DocumentRenderer;
            //docRenderer.PrepareDocument();

            //docRenderer.RenderObject(gfx, XUnit.FromCentimeter(5), XUnit.FromCentimeter(10), "12cm", paragraph);

            MemoryStream m = new MemoryStream();
            doc.Save(m, false);
            return new FileStreamResult(m, "application/pdf");
        }

        public ActionResult TestPdfSharp1()
        {
            PdfDocument doc = new PdfDocument();
            doc.Info.Title = "Member information";
            doc.Info.Author = "PalangPanya";
            doc.Info.Subject = "Member information";
            doc.Info.Keywords = "PalangPanya";

            PdfPage page = doc.AddPage();
            XGraphics gfx = XGraphics.FromPdfPage(page);
            gfx.MUH = PdfFontEncoding.Unicode;
            gfx.MFEH = PdfFontEmbedding.Default;
            XFont font = new XFont("Cordia New", 16, XFontStyle.Bold);
            gfx.DrawString("The following paragraph was rendered using ภาษาภ", font, XBrushes.Black, new XRect(100, 100, page.Width - 200, 300), XStringFormats.Center);


            XPen pen = new XPen(XColors.Navy, Math.PI);

            gfx.DrawRectangle(pen, 10, 0, 100, 60);
            gfx.DrawRectangle(XBrushes.DarkOrange, 130, 0, 100, 60);
            gfx.DrawRectangle(pen, XBrushes.DarkOrange, 10, 80, 100, 60);
            gfx.DrawRectangle(pen, XBrushes.DarkOrange, 150, 80, 60, 60);





            Document document = new Document();
            Section sec = document.AddSection();

            Paragraph para = sec.AddParagraph();
            para.Format.Alignment = ParagraphAlignment.Justify;
            para.Format.Font.Name = "Times New Roman";
            para.Format.Font.Size = 12;
            para.Format.Font.Color = MigraDoc.DocumentObjectModel.Colors.DarkGray;
            para.Format.Font.Color = MigraDoc.DocumentObjectModel.Colors.DarkGray;
            para.AddText("Duisism odigna acipsum delesenisl ");
            para.AddFormattedText("ullum in velenit", TextFormat.Bold);
            para.AddText(" ipit iurero dolum zzriliquisis nit wis dolore vel et nonsequipit, velendigna " +
              "auguercilit lor se dipisl duismod tatem zzrit at laore magna feummod oloborting ea con vel " +
              "essit augiati onsequat luptat nos diatum vel ullum illummy nonsent nit ipis et nonsequis " +
              "niation utpat. Odolobor augait et non etueril landre min ut ulla feugiam commodo lortie ex " +
              "essent augait el ing eumsan hendre feugait prat augiatem amconul laoreet. ≤≥≈≠");
            para.Format.Borders.Distance = "5pt";
            para.Format.Borders.Color = Colors.Gold;





            //Paragraph paragraph = sec.AddParagraph();

            //paragraph.Format.Font.Color = Color.FromCmyk(100, 30, 20, 50);

            //paragraph.AddFormattedText("Hello,ไทย World!", TextFormat.Bold);

PPtest/src/PPtest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PPtest</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.ApplicationInsightsJavaScript(TelemetryConfiguration)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">PPtest</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            iText
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="Home" asp-action="iTextFontList">iTextFontList</a></li>
                            <li><a asp-controller="Home" asp-action="iTextDetailsPdfSample">iTextDetailsPdfSample</a></li>
                            <li><a asp-controller="Home" asp-action="iTextDetailsPdf">iTextDetailsPdf</a></li>
                            <li><a asp-controller="Home" asp-action="iTextDetailsHtmlToPdf">iTextDetailsHtmlToPdf</a></li>
                            <li><a asp-controller="Home" asp-action="iTextDetailsPdfTest">iTextDetailsPdfTest</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            PdfSharp
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="PdfSharpTest" asp-action="TestMigraDoc1">Test1</a></li>
                            <li><a asp-controller="PdfSharpTest" asp-action="TestMigraDocMixPdfSharp">Test2</a></li>
                            <li><a asp-controller="PdfSharpTest" asp-action="TestPdfSharp1">TestPdfSharp1</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Test EMail
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="EMail" asp-action="send">test send mail</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Authentication & Authorization
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="AA" asp-action="Login">Login</a></li>
                        </ul>
                    @if (await AuthorizationService.AuthorizeAsync(User, "OperationRights"))
            		{
                        <li>
                        	<a asp-controller="AA" asp-action="Login">Test</a></li>
                        </ul>
            		}
        		    @if (await AuthorizationService.AuthorizeAsync(User, "AdministratorRights"))
                    {
                    	<li>
                        	<a asp-controller="AA" asp-action="Login">Test2</a></li>
                        </ul>
                    }
                    </li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - PPtest</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>