PPcore/src/PPcore/Models/album.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PPcore.Models
{
    public partial class album
    {
        [HiddenInput]
        public string album_code { get; set; }

        [Display(Name = "ชื่ออัลบั้ม")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        public string album_name { get; set; }

        [Display(Name = "คำอธิบาย")]
        public string album_desc { get; set; }

        [HiddenInput]
        public string album_type { get; set; }

        [Display(Name = "สร้างโดย")]
        [HiddenInput]
        public string created_by { get; set; }

        [Display(Name = "วันที่")]
        [Required(ErrorMessage = "กรุณากรอกข้อมูล")]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd MMMM yyyy}")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        public DateTime album_date { get; set; }

        public string x_status { get; set; }
        public string x_note { get; set; }
        public string x_log { get; set; }
        public Guid id { get; set; }

        [HiddenInput]
        public byte[] rowversion { get; set; }
    }
}

PPcore/src/PPcore/Controllers/albumsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPcore.Models;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.Net.Http.Headers;
using Newtonsoft.Json;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json.Linq;

namespace PPcore.Controllers
{
    public class albumsController : Controller
    {
        private readonly PalangPanyaDBContext _context;
        private IConfiguration _configuration;
        private IHostingEnvironment _env;

        public albumsController(PalangPanyaDBContext context, IConfiguration configuration, IHostingEnvironment env)
        {
            _context = context;
            _configuration = configuration;
            _env = env;
        }

        // GET: albums
        public async Task<IActionResult> Index()
        {
            var album = _context.album.Where(a => a.album_type == "P");
            ViewBag.countRecords = album.Count();
            return View(await album.OrderByDescending(m => m.album_date).ToListAsync());
        }

        // GET: albums/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.album.SingleOrDefaultAsync(m => m.id == new Guid(id));
            if (album == null)
            {
                return NotFound();
            }
            var appId = _configuration.GetSection("facebook").GetSection("AppId").Value;
            ViewBag.FormAction = "Details";
            ViewBag.album_code = album.album_code;
            ViewBag.appId = appId;
            return View(album);
        }

        // GET: albums/Create
        public IActionResult Create()
        {
            ViewBag.FormAction = "Create";
            ViewBag.album_code = DateTime.Now.ToString("yyMMddhhmmss");
            return View();
        }

        // POST: albums/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("album_code,album_desc,album_name,created_by,album_date,rowversion")] album album)
        {
            album.album_type = "P"; //pictures
            album.x_status = "Y";
            album.created_by = "Administrator";

            _context.Add(album);
            _context.SaveChanges();

            var pImages = _context.pic_image.Where(p => (p.ref_doc_code == album.album_code) && (p.x_status == "N")).ToList();
            if (pImages != null)
            {
                foreach (var pImage in pImages)
                {
                    pImage.x_status = "Y";
                    _context.Update(pImage);
                }
                _context.SaveChanges();

                var uploads = Path.Combine(_env.WebRootPath, _configuration.GetSection("Paths").GetSection("images_upload").Value);
                uploads = Path.Combine(uploads, album.album_code);

                DirectoryInfo di = new DirectoryInfo(uploads);
                if (di.Exists)
                {
                    var dest = Path.Combine(_env.WebRootPath, _configuration.GetSection("Paths").GetSection("images_album").Value);
                    dest = Path.Combine(dest, album.album_code);
                    Directory.Move(uploads, dest);
                }
            }
            return RedirectToAction("Index");
        }

        // GET: albums/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var album = await _context.album.SingleOrDefaultAsync(m => m.id == new Guid(id));
            if (album == null)
            {
                return NotFound();
            }

            clearImageUpload(album.album_code);

            ViewBag.FormAction = "Edit";
            ViewBag.album_code = album.album_code;
            return View(album);
        }

        // POST: albums/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(string id, [Bind("album_code,album_desc,album_name,album_type,created_by,album_date,id,rowversion,x_log,x_note,x_status")] album album)
        {
            try
            {
                _context.Update(album);
                _context.SaveChanges();

                var pImages = _context.pic_image.Where(p => (p.ref_doc_code == album.album_code) && (p.x_status == "N")).ToList();
                if (pImages != null)
                {
                    foreach (var pImage in pImages)
                    {
                        pImage.x_status = "Y";
                        _context.Update(pImage);
                    }
                    _context.SaveChanges();

                    var uploads = Path.Combine(_env.WebRootPath, _configuration.GetSection("Paths").GetSection("images_upload").Value);
                    uploads = Path.Combine(uploads, album.album_code);

                    DirectoryInfo di = new DirectoryInfo(uploads);
                    if (di.Exists)
                    {
                        var dest = Path.Combine(_env.WebRootPath, _configuration.GetSection("Paths").GetSection("images_album").Value);
                        dest = Path.Combine(dest, album.album_code);
                        Directory.CreateDirectory(dest);
                        foreach (FileInfo file in di.GetFiles()) file.CopyTo(Path.Combine(dest, file.Name));
                        di.Delete(true);
                    }
                }
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!albumExists(album.album_code))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction("Index");

        }

        // Get: albums/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var album = await _context.album.SingleOrDefaultAsync(m => m.id == new Guid(id));
            //var albumImage = await _context.album_image
            _context.album.Remove(album);
            await _context.SaveChangesAsync();
            return Json(new { result = "success" });
        }

        private bool albumExists(string id)
        {
            return _context.album.Any(e => e.album_code == id);
        }

        [HttpPost]
        public IActionResult UploadAlbumPhoto(ICollection<IFormFile> file, string albumCode)
        {
            var uploads = Path.Combine(_env.WebRootPath, _configuration.GetSection("Paths").GetSection("images_upload").Value);
            uploads = Path.Combine(uploads, albumCode);
            Directory.CreateDirectory(uploads);

            var fileName = ""; var fileExt = ""; var imageCode = "";
            foreach (var fi in file)
            {
                if (fi.Length > 0)
                {
                    fileName += Microsoft.Net.Http.Headers.ContentDispositionHeaderValue.Parse(fi.ContentDisposition).FileName.Trim('"');
                    fileExt = Path.GetExtension(fileName);
                    fileName = Path.GetFileNameWithoutExtension(fileName);
                    fileName = fileName.Substring(0, (fileName.Length <= (50-fileExt.Length) ? fileName.Length : (50 - fileExt.Length))) + fileExt;
                    
                    imageCode = "A" + DateTime.Now.ToString("yyMMddhhmmssfffffff") + fileExt;
                    using (var SourceStream = fi.OpenReadStream())
                    {
                        using (var fileStream = new FileStream(Path.Combine(uploads, imageCode), FileMode.Create))
                        {
                            SourceStream.CopyTo(fileStream);
                            
                            pic_image pic_image = new pic_image();
                            pic_image.image_code = imageCode;
                            pic_image.x_status = "N";
                            pic_image.image_name = fileName;
                            pic_image.image_desc = fileName;
                            pic_image.ref_doc_type = "album";
                            pic_image.ref_doc_code = albumCode;
                            _context.pic_image.Add(pic_image);
                            _context.SaveChanges();
                        }
                    }
                }
            }
            return Json(new { result = "success", uploads = uploads, fileName = fileName });
        }

        [HttpGet]
        public IActionResult ListAlbumPhoto(string albumCode)
        {
            album album = _context.album.SingleOrDefault(m => m.album_code == albumCode);
            var abName = album.album_name;
            var abDesc = album.album_desc;

            var fiN = ""; var fiP = "";
            List<photo> ph = new List<photo>();
            var pImages = _context.pic_image.Where(p => (p.ref_doc_code == albumCode) && (p.x_status == "Y")).ToList();
            if (pImages != null)
            {
                foreach (var pImage in pImages)
                {
                    fiN = pImage.image_code;
                    fiP = Path.Combine(albumCode, fiN);
                    fiP = Path.Combine(_configuration.GetSection("Paths").GetSection("images_album").Value, fiP);
                    if (pImage.image_desc == null) { pImage.image_desc = ""; }

PPcore/src/PPcore/Views/albums/Create.cshtml
<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12" style="padding-top:15px;">
            <table><tr><td><h4 class="txt-color-blue">ภาพกิจกรรม</h4></td></tr></table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading">
                    <div class="pull-left" style="padding-top:5px;">ภาพกิจกรรม</div>

                    <!--
                    <div class="pull-right" style="position:relative;top:-55px;margin-right:.5em;float:right"> 
                        <button id="btnSave" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-floppy-o" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;จัดเก็บ&nbsp;&nbsp;</button>
                    </div>
                    -->
                    <div class="pull-right" style="margin-top:-2px;">
                        <button id="btnBack" class="btn btn-default btn-panel-yellow" onclick="location.href='@Url.Action("Index", "albums")'">&nbsp;<i class="fa fa-reply" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;กลับ&nbsp;&nbsp;</button>
                    </div>
                </div>

                <!-- /.panel-heading -->

                <div class="panel-body">
                    @{ await Html.RenderPartialAsync("ViewInput"); }
                </div>
                <!-- /.panel-body -->
            </div>

            <!-- /.panel -->
        </div>
        <!-- /.col-lg-8 -->



    </div>
</div>



@section Scripts {
    <script src="~/lib/bootstrap/js/modal.js"></script>
    <script>
        $(document).ready(function () {
            $.datepicker.regional['th'] = {
                dateFormat: 'dd-mm-yy', changeMonth: true, changeYear: true, constrainInput: true,
                yearRange: "-100:+0", yearOffSet: 543,beforeShow:dateDefault
            };
            $.datepicker.setDefaults($.datepicker.regional['th']);
            $("#album_date").datepicker($.datepicker.regional["th"]);

            if ("@ViewBag.FormAction" == "Create") {
                $("#album_code").val('@ViewBag.album_code');
            }

            $('#btnSaveX').on('click', function (e) {
                e.preventDefault();
                $.ajax({
                    async:false,
                    type: "POST",
                    url: "@Url.Action("Create", "albums")",
                    data: {
                        album_name: $("#album_name").val(),
                        album_desc: $("#album_desc").val(),
                        album_date: $("#album_date").val(),
                    },
                    success: function (data) {
                        window.location.href = "@Url.Action("Index", "albums")";
                    }
                });
            });
        });
        $('#album_dateButton').click(function () {
            $('#album_date').datepicker("show");
        });
        function dateDefault() {
            if ($("#album_date").val() == "") { $("#album_date").datepicker("setDate", new Date()); }
        }
    </script>
}

PPcore/src/PPcore/Views/albums/Index.cshtml
@model IEnumerable<PPcore.Models.album>

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12" style="padding-top:15px;">
            <table><tr><td><h4 class="txt-color-blue">ภาพกิจกรรม</h4></td></tr></table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading">
                    <div class="pull-left" style="padding-top:5px;">ภาพกิจกรรม</div>
                    <div class="pull-right" style="margin-top:-2px;">
                        <button id="btnCreate" class="btn btn-default btn-panel-yellow" onclick="location.href='@Url.Action("Create", "albums")'">&nbsp;<i class="fa fa-file" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;สร้างอัลบั้ม&nbsp;&nbsp;&nbsp;</button>
                        <button id="btnEdit" class="btn btn-default btn-panel-yellow" >&nbsp;<i class="fa fa-pencil-square-o" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;แก้ไขอัลบั้ม&nbsp;&nbsp;&nbsp;</button>
                        <button id="btnDelete" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-eraser" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;ลบอัลบั้ม&nbsp;&nbsp;&nbsp;</button>
                        <button id="btnDetails" class="btn btn-default btn-panel-yellow" >&nbsp;<i class="fa fa-file-text" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;ดูข้อมูลและแชร์ภาพ</button>
                    </div>
                </div>

                <!-- /.panel-heading -->
                <div style="position:absolute;left:250px;top:70px;"><span class="badge">จำนวนรายการทั้งหมด @ViewBag.countRecords รายการ</span></div>
                <div class="panel-body">
                    <div class="dataTable_wrapper" style="padding-right:10px;">
                        <table class="table table-striped table-bordered table-hover" id="dataTablesSimple">
                            <thead>
                                <tr>
                                    <th>@Html.DisplayNameFor(model => model.album_name)</th>
                                    <th style="display:none">@Html.DisplayNameFor(model => model.id)</th>
                                    <th>@Html.DisplayNameFor(model => model.album_desc)</th>
                                    <th>@Html.DisplayNameFor(model => model.album_date)</th>
                                    <th>@Html.DisplayNameFor(model => model.created_by)</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@Html.DisplayFor(modelItem => item.album_name)</td>
                                        <td style="display:none">@Html.DisplayFor(modelItem => item.id)</td>
                                        <td>@Html.DisplayFor(modelItem => item.album_desc)</td>
                                        <!-- <td>@Html.DisplayFor(modelItem => item.album_date)</td> -->
                                        <td>@String.Format("{0:dd MMMM yyyy}",item.album_date)</td>
                                        <td>@Html.DisplayFor(modelItem => item.created_by)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>




                    </div>
                </div>
                <!-- /.panel-body -->
            </div>

            <!-- /.panel -->
        </div>
        <!-- /.col-lg-8 -->

        <!-- Modal Delete -->
        <div class="modal fade modalForm1" id="albumDeleteModal" tabindex="-1" role="dialog" aria-labelledby="albumModalLabel" aria-hidden="true" >
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id="albumModalHeader" class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="vertical-align:middle;top:15px">&times;</button>
                        <h4 class="modal-title" id="albumModalLabel" style="vertical-align:middle;"></h4>
                    </div>
                    <div class="modal-body container-fluid">
                        <div class="row">
                            <div class="col-md-3"><div class="pull-right">@Html.DisplayNameFor(model => model.album_name)</div></div>
                            <div id="albumDeleteName" class="col-md-9" style="color:orangered"></div>
                        </div>
                        <br/>
                        <div class="row">
                            <div class="col-md-3"><div class="pull-right">@Html.DisplayNameFor(model => model.album_date)</div></div>
                            <div id="albumDeleteDate" class="col-md-9" style="color:orangered"></div>
                        </div>
                        <br/>
                        <br/>
                        <div class="row">
                            <div class="col-md-4"><button id="btnDeleteConfirm" class="btn btn-danger pull-right">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ยืนยัน&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button></div>
                            <div class="col-md-4 col-md-offset-4">
                                <button id="albumDeleteCancel" class="btn btn-default" data-dismiss="modal">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ยกเลิก&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


@section Scripts {
    <script src="~/lib/bootstrap/js/modal.js"></script>
    <script>
        $(document).ready(function () {
            var tableMember = setDataTablesSimple();
            tableMember.$('tr:first').click();

            $('#btnEdit').on('click', function () {
                var data = tableMember.row('.selected').data();
                var url = '@Url.Action("Edit", "albums", new { id = "__id__" })';
                window.location.href = url.replace('__id__', data[1]);
            });

            $('#btnDelete').on('click', function () {
                var datarow = tableMember.row('.selected').data();
                $('#albumModalLabel').text('ยืนยันการลบอัลบั้ม');
                $('#albumDeleteName').text(datarow[0]);
                $('#albumDeleteDate').text(datarow[3]);
                $('#albumDeleteModal').modal({ backdrop: 'static', keyboard: false });
            });
            $('#btnDeleteConfirm').on('click', function () {
                var datarow = tableMember.row('.selected').data();
                $.ajax({
                    type: "GET",
                    url: "@Url.Action("Delete", "albums")" + "/" + datarow[1],
                    success: function (data) {
                        $('#albumDeleteModal').modal('hide');
                        window.location.href = '@Url.Action("Index", "albums")';
                    },
                    error: function (xhr, textStatus, error) {
                        console.log(xhr.statusText);
                        console.log(textStatus);
                        console.log(error);
                        $('#albumDeleteModal').modal('hide');
                        window.location.href = '@Url.Action("Index", "albums")';
                    }
                  
                });
            });

            $('#btnDetails').on('click', function () {
                var data = tableMember.row('.selected').data();
                var url = '@Url.Action("Details", "albums", new { id = "__id__" })';
                window.location.href = url.replace('__id__', data[1]);
            });
        });

    </script>
}

PPcore/src/PPcore/Views/albums/ViewInput.cshtml
@model PPcore.Models.album

<div class="row">

    <div class="col-md-2">
        <form asp-action="@ViewBag.FormAction">
            <div class="form-horizontal">


                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="rowversion" />
                <input asp-for="album_code" /><input asp-for="album_type" /><input asp-for="created_by" />
                <div class="form-group">
                    <div class="row col-md-offset-1">
                        <label asp-for="album_name" class="control-label"></label>
                        <input asp-for="album_name" class="form-control" maxlength="100" />
                        <span asp-validation-for="album_name" class="text-danger" />
                    </div>
                    <div class="row col-md-offset-1">
                        <label asp-for="album_desc" class="control-label"></label>
                        <textarea asp-for="album_desc" class="form-control" rows="3" maxlength="200" style="resize:none;"></textarea>
                        <span asp-validation-for="album_desc" class="text-danger" />
                    </div>
                    <div class="row col-md-offset-1">
                        <label asp-for="album_date" class="control-label"></label>
                        <div class="input-group">
                            <input asp-for="album_date" class="form-control" readonly>
                            <span class="input-group-btn">
                                <button id="album_dateButton" class="btn btn-default" type="button" style="border-color:orangered;">
                                    <i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                        <span asp-validation-for="album_date" class="text-danger" />
                    </div>
                    <div class="row col-md-offset-1">
                        <br />
                        <button id="btnSave" type="submit" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-floppy-o" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;จัดเก็บ&nbsp;&nbsp;</button>
                    </div>
                </div>


            </div>
        </form>
    </div>


    <div class="col-md-10">
        <form action="@Url.Action("UploadAlbumPhoto", "albums", new {albumCode=ViewBag.album_code})" class="dropzone">
            <div class="dz-message pull-left" data-dz-message>
                <div style="background-color:#ffC000;height:290px;width:80px;left:40px;top:25px;position:absolute;border-radius:5px;">
                    <i class="fa fa-plus-square-o txt-color-blue" aria-hidden="true" style="position:relative;left:-1px;top:20px;font-size:50px;"></i>
                </div>
            </div>
            <div class="dz-message" data-dz-message>
                <span style="font-size:20px;">เพิ่มรูปภาพ</span>
            </div>
        </form>
    </div>


</div>
<br />
@if (ViewBag.FormAction == "Edit")
{
    <div class="row">
        <div class="col-md-12">
            <div id="albumPanel" class="well" style="padding-left:10px;padding-top:0px;">
                <div id="isMarkAll" style="display:none">0</div>
                <div class="photo-mark" style="position:relative;width:100%" onclick="markAllPhoto();">&nbsp;<br/>&nbsp;
                    <div style="position:absolute;top:0px;right:3px;width:120px;">
                        <div style="position:absolute;left:5px;top:8px;"><div id="markAllPhoto" aria-hidden="true" style="font-size:28px;"><i class="fa fa-square-o" aria-hidden="true"></i></div></div>
                        <div style="position:absolute;left:35px;top:15px;"><div style="font-size:16px;">เลือกทั้งหมด</div></div>
                    </div>
                    <br/>
                </div>
                <!--  border: 1px solid #ccc;margin-left:20px;margin: 20px 0; -->
            </div>
        </div>
    </div>

}

<br /><br />