PPcore/src/PPcore/Models/project_daily_checklist.cs
using System;
using System.Collections.Generic;

namespace PPcore.Models
{
    public partial class project_daily_checklist
    {
        public string course_code { get; set; }
        public string member_code { get; set; }
        public DateTime course_date { get; set; }
        public string x_status { get; set; }
        public string x_note { get; set; }
        public string x_log { get; set; }
        public Guid id { get; set; }
    }
}

PPcore/src/PPcore/ViewModels/project_daily_checklist/memberViewModel.cs
using System.ComponentModel.DataAnnotations;


namespace PPcore.ViewModels.project_daily_checklist
{
    public class memberViewModel
    {
        public Models.member member { get; set; }
        [Display(Name = "เช็คชื่อเข้าอบรม")]
        public string attended { get; set; }
    }
}

PPcore/src/PPcore/Controllers/project_daily_checklistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PPcore.Models;

namespace PPcore.Controllers
{
    public class project_daily_checklistController : Controller
    {
        private readonly PalangPanyaDBContext _context;

        public project_daily_checklistController(PalangPanyaDBContext context)
        {
            _context = context;    
        }

        public IActionResult Index()
        {
            ViewBag.countRecords = _context.project_course.Where(m => m.x_status != "N").Count();
            return View();
        }

        [HttpGet]
        public IActionResult DetailsAsTableCourse()
        {
            var p = _context.project_course.Where(m => m.x_status != "N").OrderBy(m => m.course_code);
            return View(p.ToList());
        }

        public async Task<IActionResult> DetailsCourse(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var project_course = await _context.project_course.SingleOrDefaultAsync(m => m.id == new Guid(id));
            if (project_course == null)
            {
                return NotFound();
            }
            ViewBag.ctype_code = project_course.ctype_code;
            if ((project_course.course_end == null) || (project_course.course_end <= project_course.course_begin))
            {
                ViewBag.course_day = new SelectList(new[] { new { Value = "1", Text = "1" } }, "Value", "Text", "1");
            }
            else
            {
                TimeSpan ts = (DateTime)project_course.course_end - (DateTime)project_course.course_begin;
                List<SelectListItem> items = new List<SelectListItem>();
                for (int i = 1; i <= (ts.Days + 1);i++)
                {
                    items.Add(new SelectListItem() { Text = i.ToString(), Value = i.ToString() });
                }
                ViewBag.course_day = new SelectList(items, "Value", "Text", "1");
            }
            ViewBag.cgroup_code = new SelectList(_context.course_group.Where(cg => cg.x_status != "N").OrderBy(cg => cg.cgroup_code), "cgroup_code", "cgroup_desc", 1);
            ViewBag.active_member_join = _context.project_course_register.Where(pcr => pcr.course_code == project_course.course_code).Count();
            ViewBag.passed_member = _context.project_course_register.Where(p => (p.course_code == project_course.course_code) && (p.course_grade >= project_course.passed_score)).Count();
            return View(project_course);
        }

        [HttpGet]
        public IActionResult DetailsAsTableMember(string course_code, int course_day)
        {
            var ps = _context.project_course_register.Where(pp => pp.course_code == course_code).OrderBy(pp => pp.member_code).ToList();
            var c = _context.project_course.SingleOrDefault(cc => cc.course_code == course_code);
            var cdate = ((DateTime)c.course_begin).AddDays(course_day - 1);
            List<ViewModels.project_daily_checklist.memberViewModel> pms = new List<ViewModels.project_daily_checklist.memberViewModel>();

            foreach (project_course_register p in ps)
            {
                var m = _context.member.SingleOrDefault(mm => mm.member_code == p.member_code);
                var pc = _context.project_daily_checklist.SingleOrDefault(pcc => (pcc.member_code == m.member_code) && (pcc.course_code == course_code) && (pcc.course_date == cdate));
                ViewModels.project_daily_checklist.memberViewModel pd = new ViewModels.project_daily_checklist.memberViewModel();
                pd.member = m;
                if (pc == null) { pd.attended = "N"; } else { pd.attended = "Y"; }
                pms.Add(pd);
            }
            return View(pms);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string action, string member_code, string course_code, DateTime course_begin, int course_day)
        {
            var cdate = course_begin.AddDays(course_day-1);

            try
            {

                if (action.Equals("add"))
                {
                    var c = new project_daily_checklist();
                    c.member_code = member_code;
                    c.course_code = course_code;
                    c.course_date = cdate;
                    c.x_status = "Y";
                    _context.Add(c);
                }
                else if (action.Equals("del"))
                {
                    var c = _context.project_daily_checklist.SingleOrDefault(d => (d.member_code == member_code) && (d.course_code == course_code) && (d.course_date == cdate));
                    _context.Remove(c);
                }
                await _context.SaveChangesAsync();
            }
            catch (Exception)
            {
                return Json(new { result = "fail" });
            }
            return Json(new { result = "success" });
        }
    }
}

PPcore/src/PPcore/Views/project_daily_checklist/DetailsAsTableCourse.cshtml
@model IEnumerable<PPcore.Models.project_course>
@{
    Layout = null;
}


<table class="table table-striped table-bordered table-hover" id="a_table">
    <thead>
        <tr>
            <th style="width:15px;">ลำดับ</th>
            <th style="display:none">@Html.DisplayNameFor(model => model.id)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.course_code)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.project_code)</th>
            <th>@Html.DisplayNameFor(model => model.course_desc)</th>
            <th style="width:50px;">@Html.DisplayNameFor(model => model.x_status)</th>
            <th>เช็คชื่อเข้าอบรม</th>

        </tr>
    </thead>
    <tbody>
        @{ var countOrder = 0;}
        @foreach (var item in Model)
        {
            countOrder++;
            <tr>
                <td style="width:15px;">@countOrder</td>
                <td style="display:none">@Html.DisplayFor(modelItem => item.id)</td>
                <td>@Html.DisplayFor(modelItem => item.course_code)</td>
                <td>@Html.DisplayFor(modelItem => item.project_code)</td>
                <td>@Html.DisplayFor(modelItem => item.course_desc)</td>
                <td>@Html.x_status_text(item.x_status)</td>
                <td id="cell-@Html.DisplayFor(modelItem => item.id)"><button class="btn btn-xs btn-panel-yellow" type="button" onclick="detailsClick('@Html.DisplayFor(modelItem => item.id)');">รายชื่อผู้เข้าอบรม</button></td>
            </tr>
        }
    </tbody>
</table>

PPcore/src/PPcore/Views/project_daily_checklist/DetailsAsTableMember.cshtml
@model IEnumerable<PPcore.ViewModels.project_daily_checklist.memberViewModel>
@{
    Layout = null;
}

<table class="table table-striped table-bordered table-hover" id="a_table">
    <thead>
        <tr>
            <th style="width:15px;">ลำดับ</th>
            <th style="display:none">@Html.DisplayNameFor(model => model.member.id)</th>
            <th style="width:70px;">@Html.DisplayNameFor(model => model.member.member_code)</th>
            <th style="width:50px;">@Html.DisplayNameFor(model => model.member.title)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.member.fname)</th>
            <th>ที่อยู่</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.member.mobile)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.member.email)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.member.line)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.member.facebook)</th>
            <th style="width:150px;">@Html.DisplayNameFor(model => model.attended)</th>
        </tr>
    </thead>
    <tbody>
        @{ var countOrder = 0; }
        @foreach (var item in Model)
        {
            countOrder++;
            <tr>
                <td style="width:15px;">@countOrder</td>
                <td style="display:none">@Html.DisplayFor(modelItem => item.member.id)</td>
                <td>@Html.DisplayFor(modelItem => item.member.member_code)</td>
                <td>@Html.DisplayFor(modelItem => item.member.title)</td>
                <td>@Html.DisplayFor(modelItem => item.member.fname) @Html.DisplayFor(modelItem => item.member.lname)</td>
                <td>@Html.DisplayFor(modelItem => item.member.texta_address) @Html.DisplayFor(modelItem => item.member.textb_address) @Html.DisplayFor(modelItem => item.member.textc_address)</td>
                <td>@Html.DisplayFor(modelItem => item.member.mobile)</td>
                <td>@Html.DisplayFor(modelItem => item.member.email)</td>
                <td>@Html.DisplayFor(modelItem => item.member.line)</td>
                <td>@Html.DisplayFor(modelItem => item.member.facebook)</td>
                <td style="text-align:center">
                    @if (item.attended == "Y")
                    {
                        <button id="cell-@Html.DisplayFor(modelItem => item.member.id)" class="btn btn-xs btn-panel-green-attended" type="button" onclick="attendClick('@Html.DisplayFor(modelItem => item.member.id)','@Html.DisplayFor(modelItem => item.member.member_code)');">
                        <i class='fa fa-check-square-o' aria-hidden='true'></i> ลงชื่อแล้ว
                        </button>
                    }
                    else
                    {
                        <button id="cell-@Html.DisplayFor(modelItem => item.member.id)" class="btn btn-xs btn-panel-yellow" type="button" onclick="attendClick('@Html.DisplayFor(modelItem => item.member.id)','@Html.DisplayFor(modelItem => item.member.member_code)');">
                        <i class='fa fa-square-o' aria-hidden='true'></i> เช็คชื่อเข้าอบรม
                        </button>
                    }
                    
                    @*<div id="" aria-hidden="true" style="font-size:25px;" onclick=""><i class="fa fa-square-o" aria-hidden="true"></i></div>
                    <div id="" aria-hidden="true" style="font-size:25px;" onclick=""><i class="fa fa-check-square-o" aria-hidden="true"></i></div>*@
                </td>
            </tr>
        }
    </tbody>
</table>

PPcore/src/PPcore/Views/project_daily_checklist/Edit.cshtml
@model PPcore.Models.project_daily_checklist

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>project_daily_checklist</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="course_date" />
    <input type="hidden" asp-for="course_code" />
    <input type="hidden" asp-for="member_code" />
        <div class="form-group">
            <label asp-for="id" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="id" class="form-control" />
                <span asp-validation-for="id" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="x_log" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="x_log" class="form-control" />
                <span asp-validation-for="x_log" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="x_note" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="x_note" class="form-control" />
                <span asp-validation-for="x_note" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="x_status" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="x_status" class="form-control" />
                <span asp-validation-for="x_status" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PPcore/src/PPcore/Views/project_daily_checklist/Index.cshtml
@model PPcore.Models.project_course

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12" style="padding-top:15px;">
            <table><tr><td><h4 class="txt-color-blue">เช็คชื่อเข้าอบรม</h4></td></tr></table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-blue">
                <div class="panel-heading">
                    <div class="pull-left" style="padding-top:5px;">แสดงข้อมูลทั้งหมด</div>
                    @*<div class="pull-right" style="margin-top:-2px;">
                        กดปุ่มเพิ่ม ถ้าต้องการใส่มากกว่า 1 รายการ&nbsp;&nbsp;&nbsp;
                        <button id="btnCreate" class="btn btn-default btn-panel-yellow" onclick="location.href='@Url.Action("CourseCreate", "project_course")'">&nbsp;<i class="fa fa-file" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;&nbsp;เพิ่ม&nbsp;&nbsp;&nbsp;&nbsp;</button>
                        <button id="btnEdit" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-pencil-square-o" aria-hidden="true" style="color:white;"></i>&nbsp;แก้ไข&nbsp;&nbsp;</button>
                        <button id="btnDetails" class="btn btn-default btn-panel-yellow">&nbsp;<i class="fa fa-file-text" aria-hidden="true" style="color:white;"></i>&nbsp;&nbsp;ดูข้อมูล</button>
                    </div>*@
                </div>

                <!-- /.panel-heading -->
                <div style="position:absolute;left:250px;top:70px;"><span class="badge">จำนวนรายการทั้งหมด @ViewBag.countRecords รายการ</span></div>
                <div class="panel-body">
                    <div class="dataTable_wrapper" style="padding-right:10px;" id="a_details_as_table">



                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
        </div>
    </div>

</div>

@section scripts {
    <script src="~/lib/bootstrap/js/modal.js"></script>
    <script>
        $(document).ready(function () {
            a_details_as_table();
        });
        function a_details_as_table() {
            $.ajax({
                type: 'get', url: '@Url.Action("DetailsAsTableCourse", "project_daily_checklist")',
            }).done(function (resp) {
                $('#a_details_as_table').html(resp);
                var w = [
                    { "targets": [0], "width": "15", "className": "dt-center" },
                    { "targets": [1], "visible": false, "searchable": false },
                    { "targets": [2], "width": "150", "className": "dt-center" },
                    { "targets": [3], "width": "150", "className": "dt-center" },
                    { "targets": [5], "width": "50", "className": "dt-center" },
                    { "targets": [6], "width": "150", "className": "dt-center" },
                ];
                var table = setTable_default($('#a_table'), w);
                table.$('tr:first').click();
            });
        }
        function detailsClick(id) {
            window.location.href = "@Url.Action("DetailsCourse", "project_daily_checklist")?id=" + id;

            @*$.ajax({
                type: 'get', url: '@Url.Action("DetailsCourse", "project_daily_checklist")?id=' + id,
            }).done(function (resp) {
                $('#a_body').html(resp);
                $('#a_label').text('ลงทะเบียน');
                $('#a_modal').modal({ backdrop: 'static', keyboard: false });

                $('#a_submit').off('click').on('click', function () {
                    $('#a_modal').modal('hide');
                    $('#courseId').val(id); $('#cid').val(''); $('#cidmsg').text('');
                    $('#confirm_modal').modal({ backdrop: 'static', keyboard: false });
                });

            });*@
        }
    </script>
}